Repository cacounicamp/Manual-do-Bixo, pull requests merged in 2018-12, with the labels that each got.

#182 Adicionando seção de caixas eletrônicos em Barão (Closes #163)
  02-barao/outras_necessidades.tex
Labels: enhancement, ongoing

#180 Links, telefones e endereços desatualizados (Closes #169)
  02-barao/comida.tex
  02-barao/diversao.tex
  02-barao/lugares_para_morar.tex
  02-barao/outras_necessidades.tex
  03-unicamp/bem_vindo_a_academia.tex
  03-unicamp/disciplinas.tex
Labels: enhancement, fix, ongoing

#178 Adicionando canal no Youtube da Phoenix (Closes #175, closes #171)
  04-alem_da_graduacao/grupos_entidades.tex
Labels: enhancement, ongoing

#190 Adicionando alguns comércios novos (Closes #165)
  02-barao/comida.tex
Labels: ongoing
